# action.yml
name: 'build manylinux wheel'
inputs:
  python-version:
    required: true
    default: '3.7 3.8 3.9'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.python-version }}
branding:
  icon: 'package'
  color: 'green'
