name: build

on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.python }} ${{ matrix.os }} ${{ matrix.manylinux }} ${{ matrix.plat }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: [ 3.7 ]
        manylinux: [ 2010 ]
        plat: [ x86_64 ]
        macos-target: [ "10.10" ]
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build
        run: |
          which python3
          python3 -m pip install pip build twine --upgrade
          python3 -m pip install mkl==2019 mkl-include intel-openmp numpy cmake==3.17 pybind11
          ls /usr/include
          echo x
          ls /usr/local/include
          echo x
          ls /usr/include/python3.8
          echo x
          python3 -c 'import mkl; print(mkl.__file__)'
